In [1]:
import pandas as pd
import numpy as np

In [7]:
existing_data = pd.read_csv('existing_data.csv',index_col = 'Date')

In [8]:
existing_data

            24 Carat 1 Gram
Date
2023-11-30            23770
2023-11-29            23840
2023-11-28            23460
2023-11-27            23350
2023-11-24            23150
2023-11-23            23160
2023-11-22            23170
2023-11-21            23080
2023-11-20            22990
2023-11-17            23020
2023-11-16            22790
2023-11-15            22730
2023-11-14            22480
2023-11-13            22440
2023-11-10            22730
2023-11-09            22660
2023-11-08            22780
2023-11-07            22880
2023-11-06            23150
2023-11-03            23100
2023-11-02            23030
2023-11-01            22920
2023-10-31            23100
2023-10-30            23180
2023-10-27            22940
2023-10-26            22920
2023-10-25            22840
2023-10-24            22810
2023-10-23            22650
2023-10-20            22730
2023-10-19            22350
2023-10-18            22250
2023-10-17            21900
2023-10-16            22000
2023-10-13            21440
2023-10-12            21480
2023-10-11            21300
2023-10-10            21330
2023-10-09            21190
2023-10-06            20870
2023-10-05            20900
2023-10-04            20850
2023-10-03            20800
2023-10-02            21080
2023-09-27            21800
2023-09-26            21970
2023-09-25            22060
2023-09-22            22090
2023-09-21            22120
2023-09-20            22110